name: saibai_men_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.4.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^5.2.0
  flutter_riverpod: ^2.4.5
  flame: ^1.13.1
  flame_audio: ^2.1.6
  flame_forge2d: ^0.16.0+3
  flame_tiled: ^1.18.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/idle.png
    - assets/images/explosion.png
    - assets/images/enemy_transparent.png
    - assets/images/energy bullet.png
    - assets/images/energy icon.png
    - assets/sounds/explosion.mp3
    - assets/sounds/bgm.mp3
    - assets/sounds/specialMove.mp3
    - assets/images/explosion_sprite.png
flutter_launcher_icons:
  image_path: "assets/images/icon.png" # このアイコンをアプリのランチャーアイコンとして使用
  android: true
  ios: true
